defaultAssertionDataset:  gmp_quality
defaultLocation: US
defaultProject: sallybeauty-us-ga4
vars:
  OUTPUT_PROJECT: sallybeauty-us-ga4
  GA4_DATASET: analytics_320983557
  LOCAL_TIMEZONE: America/Chicago
  QUALITY_DATASET: gmp_quality
  TRANSFORMATIONS_DATASET: gmp_base_fresh
  REPORTING_DATASET: gmp_reporting_fresh
  TABLE_SUFFIX: ""


